POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "BubaDoe",
    "email": "buba@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "9a2aede1-6b04-4dd8-b29a-e47e32d49de2"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "66d48f06-4aa0-4c3b-afae-79a0b724dd57",
    "account_id_to": "1799feea-75b2-45f3-9210-a41b42bb3184",
    "amount": 50
}