POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "JaneDoe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "612dd168-e110-4e7a-b122-755532995e22"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "dc92e321-b2b1-45af-910e-598aab680f45",
    "account_id_to": "612dd168-e110-4e7a-b122-755532995e22",
    "amount": 50
}