POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "JaneDoe",
    "email": "jane@j.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "a2f3b72f-c20a-4e07-a1c2-e6d839b84952"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "abfe8897-5b87-4248-b6f7-a1275b8bc755",
    "account_id_to": "37165448-b271-4ff4-a7ad-31be0e9a1b36",
    "amount": 50
}